global:
  domainName: 'cytomine.local'

postgresql:
  storageClassName:
pims:
  imageStorage:
    storageClassName:
  tempImageStorage:
    storageClassName:
mongodb:
  storageClassName:
app_engine:
  tasks_namespace:

ingress:
  className: nginx

iam:
  lsaaiClientIdSecretName:
  lsaaiClientSecretSecretName:
  lsaaiEndpoint:

images:
  imagePullSecretsNames:
  - docker-images-pull-secret
  - docker-images-pull-secret-2
