global:
  domainName: 'cytomine.local'

postgresql:
  storageClassName:
pims:
  imageStorage:
    storageClassName:
  tempImageStorage:
    storageClassName:
  datasetImportFolder:
mongodb:
  storageClassName:
app_engine:
  tasks_namespace:

ingress:
  className: nginx

iam:
  lsaaiClientIdSecretName:
  lsaaiClientSecretSecretName:
  lsaaiEndpoint:

images:
  global_prefix: registry.cytomine.org/
  imagePullSecretsName: docker-images-pull-secret
