{{ if .Values.postgresql.deploy }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgis
  annotations:
    kube-score/ignore: pod-probes,container-security-context-user-group-id
  labels:
    role: postgresql
    app: {{ include "cytomine.name" . }}
    component: {{ .Release.Name }}-postgis
    release: {{ .Release.Name }}
spec:
  replicas: 1
  serviceName: postgis
  selector:
    matchLabels:
      app: postgis
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: postgresql
        app: postgis
        release: {{ .Release.Name }}
    spec:
      securityContext:
      {{- include "cytomine.podSecurityContext" . | nindent 8 }}
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: temp
          emptyDir: {}
        {{ if not .Values.postgresql.storageClassName -}}
        - emptyDir: {}
          name: postgres-storage
        {{ end }}
      containers:
        - name: postgis
          image: {{ .Values.images.postgresql }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
#          command: ["postgres", "-c", "config_file=/etc/postgres/postgres.conf"]
          securityContext:
          {{- include "cytomine.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
            - name: postgres-storage
              mountPath: "/var/lib/postgresql/data"
              subPath: data
            - name: postgres-storage
              mountPath: "/var/lib/postgresql"
            - name: temp
              mountPath: /var/run
            - name: temp
              mountPath: /tmp
          env:
          - name: POSTGRES_USER
            value: {{ .Values.postgresql.user }}
          - name: POSTGRES_DB
            value: {{ .Values.postgresql.database }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-core-secret
                key: password
          ports:
            - name: postgres
              containerPort: {{ .Values.postgresql.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
      initContainers:
        - name: postgis-init
          image: alpine:3.18
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          securityContext:
          {{- include "cytomine.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
            - name: postgres-storage
              mountPath: "/var/lib/postgresql/"
          command:
            - /bin/sh
            - -c
            - >
              set -x;
              mkdir -p /var/lib/postgresql/data;
              chown -R {{ .Values.containerSecurity.userID }} /var/lib/postgresql/data && chmod og-rwx /var/lib/postgresql/data;
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{ if .Values.postgresql.storageClassName -}}
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        storageClassName: {{ .Values.postgresql.storageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgresStorage }}
  {{ end }}
{{ end }}
