{{ if .Values.postgresql.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: postgis2
spec:
  clusterIP: None
  selector:
    app: postgis
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.port }}
      protocol: TCP
{{ end }}
