global:
  domainName: 'cytomine.local'

postgresql:
  storageClassName:
pims:
  imageStorage:
    storageClassName:
  tempImageStorage:
    storageClassName:
  datasetImportFolder: '/data/dataset'
mongodb:
  storageClassName:
app_engine:
  tasks_namespace:

ingress:
  className: nginx

# iam:
#   lsaaiClientIdSecretName: lsaai-client-id
#   lsaaiClientSecretSecretName: lsaai-client-secret
#   lsaaiEndpoint: https://login.aai.lifescience-ri.eu/oidc/.well-known/openid-configuration

images:
  pims_import: registry.cytomine.org/cytomine/python-client:613d3b7c9e51b52790169a9cc311c89c718e9604
  imagePullSecretsNames:
  - docker-images-pull-secret
#  - docker-images-pull-secret2
