global:
  domainName: 'cytomine.local'

postgresql:
  storageClassName:
pims:
  imageStorage:
    storageClassName:
  tempImageStorage:
    storageClassName:
  datasetImportFolder: '/data/dataset'
mongodb:
  storageClassName:
app_engine:
  tasks_namespace:

ingress:
  className: nginx

iam:
  lsaaiClientIdSecretName: lsaai-client-id
  lsaaiClientSecretSecretName: lsaai-client-secret
  lsaaiEndpoint: https://login.aai.lifescience-ri.eu/oidc/.well-known/openid-configuration

images:
  core: registry.cytomine.org/cytomine/core:fix-job-import@sha256:5dfe84ca04d4b38b89769ec347633204daab8785922f1f4531d3751b491b737f
  pims_import: registry.cytomine.org/cytomine/python-client:fix-job-import@sha256:a0f1da528ccbc3a5428d9bc861b285f37269be41db18eb6debc4f968a151d9ee
  pims: registry.cytomine.org/cytomine/pims:fix-job-import@sha256:4b4511294a0d0f6a4347edb3c020986ace6bbe32adede086ee99c7e84a93396a
  pullPolicy: IfNotPresent
