{{ if .Values.pims_cache.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pims-cache
  annotations:
    kube-score/ignore: pod-probes
  labels:
    role: pims-cache
    app: {{ include "cytomine.name" . }}
    component: {{ .Release.Name }}-pims-cache
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pims-cache
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: pims-cache
        app: pims-cache
        release: {{ .Release.Name }}
    spec:
      securityContext:
      {{- include "cytomine.podSecurityContext" . | nindent 8 }}
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: pims-cache
          image: "{{ .Values.images.pims_cache }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          securityContext:
          {{- include "cytomine.containerSecurityContext" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.pims_cache.port }}
          resources:
            {{- toYaml .Values.pims_cache.resources | nindent 12 }}
          volumeMounts:
            - name: tempdata
              mountPath: "/data"
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tempdata
          emptyDir: {}
{{ end }}
