apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-engine
  labels:
    app: app-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-engine
  template:
    metadata:
      labels:
        app: app-engine
      annotations:
        checksum/config: "{{ include (print $.Template.BasePath "/app-engine/app-engine-config.yaml") . | sha256sum }}"
    spec:
      securityContext:
      {{- include "cytomine.podSecurityContext" . | nindent 8 }}
      volumes:
        {{ if not .Values.app_engine.storage.storageClassName -}}
        - name: app-engine-storage
          emptyDir: {}
        {{ end }}
        - name: temp
          emptyDir: {}
      containers:
      - name: app-engine
        image: {{ .Values.images.app_engine }}
        securityContext:
        {{- include "cytomine.containerSecurityContext" . | nindent 12 }}
        ports:
        - containerPort: {{ .Values.app_engine.port }}
        envFrom:
        - configMapRef:
            name: app-engine
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-app-engine-secret
              key: password
        volumeMounts:
          - name: app-engine-storage
            mountPath: /data
          - name: temp
            mountPath: /tmp
      serviceAccountName: app-engine
      automountServiceAccountToken: true
  {{ if .Values.app_engine.storage.storageClassName -}}
  volumeClaimTemplates:
    - metadata:
        name: app-engine-storage
      spec:
        storageClassName: {{ .Values.app_engine.storage.storageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.app_engine.storage.size }}
  {{ end }}
