apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-app-engine
  annotations:
  labels:
    role: postgres-app-engine
    app: postgres-app-engine
    component: {{ .Release.Name }}-app-engine-postgres
    release: {{ .Release.Name }}
spec:
  replicas: 1
  serviceName: postgres-app-engine
  selector:
    matchLabels:
      app: postgres-app-engine
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: postgres-app-engine
        app: postgres-app-engine
        release: {{ .Release.Name }}
    spec:
      securityContext:
      {{- include "cytomine.podSecurityContext" . | nindent 8 }}
      volumes:
        - name: temp
          emptyDir: {}
        - name: postgres-app-engine-secret
          secret:
            secretName: postgres-app-engine-secret
        {{ if not .Values.postgresql.storageClassName -}}
        - emptyDir: {}
          name: postgres-app-engine-storage
        {{ end }}
      containers:
        - name: postgres
          image: "{{ .Values.images.postgresql_app_engine }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          securityContext:
          {{- include "cytomine.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
            - name: postgres-app-engine-storage
              mountPath: "/var/lib/postgresql/data"
              subPath: data
            - name: postgres-app-engine-storage
              mountPath: "/var/lib/postgresql"
            - name: temp
              mountPath: /var/run
            - name: temp
              mountPath: /tmp
          env:
          - name: POSTGRES_USER
            value: appengine
          - name: POSTGRES_DB
            value: appengine
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-app-engine-secret
                key: password
          ports:
            - name: postgres
              containerPort: {{ .Values.postgresql.port }}
              protocol: TCP
      initContainers:
        {{ if .Values.fixVolumesPermissions -}}
        - name: fix-previous-permissions
          image: alpine:3.18
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
          - name: postgres-app-engine-storage
            mountPath: "/var/lib/postgresql/"
          command:
            - /bin/sh
            - -c
            - >
              set -x;
              mkdir -p /var/lib/postgresql/data;
              chown -R {{ .Values.containerSecurity.userID }} /var/lib/postgresql/data;
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
        {{ end }}
        - name: postgres-init
          image: alpine:3.18
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          securityContext:
          {{- include "cytomine.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
            - name: postgres-app-engine-storage
              mountPath: "/var/lib/postgresql/"
          command:
            - /bin/sh
            - -c
            - >
              set -x;
              mkdir -p /var/lib/postgresql/data;
              chown -R {{ .Values.containerSecurity.userID }} /var/lib/postgresql/data && chmod og-rwx /var/lib/postgresql/data;
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
  {{ if .Values.postgresql.storageClassName -}}
  volumeClaimTemplates:
    - metadata:
        name: postgres-app-engine-storage
      spec:
        storageClassName: {{ .Values.postgresql.storageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgresStorage }}
  {{ end }}
