apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cbir-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cbir.storage.size | default "1Gi" }}
  {{- if .Values.cbir.storage.storageClassName }}
  storageClassName: {{ .Values.cbir.storage.storageClassName }}
  {{- end }}
