apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cbir
  labels:
    app: cbir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbir
  template:
    metadata:
      labels:
        app: cbir
      annotations:
        checksum/config: "{{ include (print $.Template.BasePath "/cbir/cbir-config.yaml") . | sha256sum }}"
    spec:
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      containers:
      - name: cbir
        image: "{{ .Values.images.cbir }}"
        ports:
        - containerPort: {{ .Values.cbir.port }}
        envFrom:
          - configMapRef:
              name: cbir
        volumeMounts:
          - name: cbir-storage
            mountPath: /data/
      {{ if not .Values.cbir.storage.storageClassName -}}
      volumes:
        - name: cbir-storage
          emptyDir: {}
      {{ end }}
  {{ if .Values.cbir.storage.storageClassName -}}
  volumeClaimTemplates:
    - metadata:
        name: cbir-storage
      spec:
        storageClassName: {{ .Values.cbir.storage.storageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.cbir.storage.size }}
  {{- end }}
