name: PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    runs-on: self-hosted

    strategy:
      fail-fast: true
      matrix:
        image:
          - name: app-engine
            context: '.'
            dockerfile_location: app-engine
          - name: cbir
          - name: core
          - name: iam
          # - name: mongo
          - name: nginx
          - name: pims
          - name: postgis
          - name: sam
          - name: web-ui
          - name: python-client
            context: clients/python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Cytomine registry
        uses: docker/login-action@v3
        with:
          registry: registry.cytomine.org
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image.context || matrix.image.name }}
          file: ./${{ matrix.image.dockerfile_location || matrix.image.context || matrix.image.name }}/Dockerfile
          push: true
          tags: registry.cytomine.org/cytomine/${{ matrix.image.name }}
          allow: network.host
          network: host
